# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78692df3d5a465ee5bc8867a11d2cbc808b1efbf3a6889beed1fa80501f3b947d7227e29d57173595d62ceeaa216eada6efb479ba69d06e3ebac9aa6f1b44402

test:
  secret_key_base: 4d06ce9f4f14467ec2519850edcc6acfee5a1c6d50ae07aed731e8c7a2761e1a3b8c97e2beaa250e5eb9f3b9556b1635788feb3c3c57fb0c331526bc58c0c02c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
